/* Copyright (c) 2013, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_SPADINA_1080P_CMD_H_

#define _PANEL_SPADINA_1080P_CMD_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/

static struct panel_config spadina_1080p_cmd_panel_data = {
  "qcom,mdss_dsi_spadina_1080p_cmd", "dsi:0:", "qcom,mdss-dsi-panel",
  10, 1, "DISPLAY_1", 0, 0, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution spadina_1080p_cmd_panel_res = {
  1080, 1920, 114, 16, 10, 0, 13, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel Color Information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info spadina_1080p_cmd_color = {
  24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel Command information                                                 */
/*---------------------------------------------------------------------------*/
static char spadina_1080p_cmd_on_cmd0[] = {
  0x03, 0x00, 0x39, 0xC0, 0xF0, 0x5A, 0x5A
};

static char spadina_1080p_cmd_on_cmd1[] = {
  0x11, 0x00, 0x05, 0x80
};

static char spadina_1080p_cmd_on_cmd2[] = {
  0x03, 0x00, 0x39, 0xC0, 0xF0, 0xA5, 0xA5
};

static char spadina_1080p_cmd_on_cmd3[] = {
  0x29, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd spadina_1080p_cmd_on_command[] = {
  { 0x7 , spadina_1080p_cmd_on_cmd0 , 0},
  { 0x4 , spadina_1080p_cmd_on_cmd1 , 20},
  { 0x7 , spadina_1080p_cmd_on_cmd2 , 120},
  { 0x4 , spadina_1080p_cmd_on_cmd3 , 0},
};
#define SPADINA_1080P_CMD_ON_COMMAND 4


static char spadina_1080p_cmdoff_cmd0[] = {
  0x28, 0x00, 0x05, 0x80
};

static char spadina_1080p_cmdoff_cmd1[] = {
  0x10, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd spadina_1080p_cmd_off_command[] = {
  { 0x4 , spadina_1080p_cmdoff_cmd0},
  { 0x4 , spadina_1080p_cmdoff_cmd1}
};
#define SPADINA_1080P_CMD_OFF_COMMAND 2


static struct command_state spadina_1080p_cmd_state = {
  0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/

static struct commandpanel_info spadina_1080p_cmd_command_panel = {
  1, 1, 1, 0, 0, 44, 0, 0, 0, 1, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/

static struct videopanel_info spadina_1080p_cmd_video_panel = {
  0, 0, 0, 0, 1, 1, 1, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane Configuration                                                        */
/*---------------------------------------------------------------------------*/

static struct lane_configuration spadina_1080p_cmd_lane_config = {
  4, 0, 1, 1, 1, 1
};


/*---------------------------------------------------------------------------*/
/* Panel Timing                                                              */
/*---------------------------------------------------------------------------*/
const uint32_t spadina_1080p_cmd_timings[] = {
  0x6e, 0x26, 0x1b, 0x00, 0x35, 0x34, 0x20, 0x28, 0x17, 0x03, 0x04, 0x00
};



static struct mipi_dsi_cmd spadina_1080p_cmd_rotation[] = {

};
#define SPADINA_1080P_CMD_ROTATION 0


static struct panel_timing spadina_1080p_cmd_timing_info = {
  0x0, 0x04, 0x02, 0x2a
};

static struct panel_reset_sequence spadina_1080p_cmd_panel_reset_seq = {
  { 1, 0, 1, }, { 20, 2, 20, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight Settings                                                        */
/*---------------------------------------------------------------------------*/

static struct backlight spadina_1080p_cmd_backlight = {
	BL_PWM, 1, 255, 0, 2, 0
};
#define SPADINA_1080P_CMD_SIGNATURE 0x210000


#endif /*_PANEL_SPADINA_1080P_CMD_H_*/
